version: '3'

services:
  postgres:
    image: postgres:9.6.6-alpine
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: quicktrip
    restart: on-failure
    ports:
      - 5432:5432
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped